# Import the necessary dtatsets

In [1]:
import pandas as pd

# read the datasets

In [2]:
correct_answer=pd.read_csv(r'correct_answer.csv')
question_paper_code=pd.read_csv(r'question_paper_code.csv')
student_list=pd.read_csv(r'student_list.csv')
student_response=pd.read_csv(r'student_response.csv')

In [3]:
student_list

     roll_number     student_name  class section           school_name
0          10001          Abhijit      6       A  Google Public School
1          10002            Aghat      6       A  Google Public School
2          10003  Amitava Chandar      6       A  Google Public School
3          10004         Anbarasu      6       A  Google Public School
4          10005       Atralarasu      6       A  Google Public School
..           ...              ...    ...     ...                   ...
236        10237           Oliver      8       C  Google Public School
237        10238            Oscar      8       C  Google Public School
238        10239           Steven      8       C  Google Public School
239        10240           Stuart      8       C  Google Public School
240        10241            Tyler      8       C  Google Public School

[241 rows x 5 columns]

In [4]:
student_response

       roll_number  question_paper_code  question_number option_marked
0            10001                  501                1             b
1            10001                  501                2             a
2            10001                  501                3             e
3            10001                  501                4             e
4            10001                  501                5             e
...            ...                  ...              ...           ...
24095        10241                  103               36             c
24096        10241                  103               37             b
24097        10241                  103               38             a
24098        10241                  103               39             c
24099        10241                  103               40             e

[24100 rows x 4 columns]

In [6]:
student_response[student_response['roll_number']==10001]

       roll_number  question_paper_code  question_number option_marked
0            10001                  501                1             b
1            10001                  501                2             a
2            10001                  501                3             e
3            10001                  501                4             e
4            10001                  501                5             e
...            ...                  ...              ...           ...
14495        10001                  101               36             e
14496        10001                  101               37             e
14497        10001                  101               38             d
14498        10001                  101               39             b
14499        10001                  101               40             b

[100 rows x 4 columns]

In [7]:
question_paper_code

   paper_code  class  subject
0         101      6     Math
1         102      7     Math
2         103      8     Math
3         501      6  Science
4         502      7  Science
5         503      8  Science

In [8]:
correct_answer

     question_paper_code  question_number correct_option
0                    101                1              d
1                    101                2              a
2                    101                3              d
3                    101                4              b
4                    101                5              d
..                   ...              ...            ...
295                  503               56              a
296                  503               57              a
297                  503               58              a
298                  503               59              c
299                  503               60              a

[300 rows x 3 columns]

# student respomse

In [13]:
student_response.head()

   roll_number  question_paper_code  question_number option_marked
0        10001                  501                1             b
1        10001                  501                2             a
2        10001                  501                3             e
3        10001                  501                4             e
4        10001                  501                5             e

In [12]:
correct_answer[correct_answer['question_paper_code']==501].head()

     question_paper_code  question_number correct_option
120                  501                1              a
121                  501                2              d
122                  501                3              a
123                  501                4              d
124                  501                5              a

In [15]:
merged_df=pd.merge(student_response,correct_answer, on=['question_paper_code','question_number'],how='inner')
merged_df

,roll_number,question_paper_code,question_number,option_marked,correct_option
0,10001,501,1,b,a
1,10001,501,2,a,d
2,10001,501,3,e,a
3,10001,501,4,e,d
4,10001,501,5,e,a
...,...,...,...,...,...
24095,10241,103,36,c,c
24096,10241,103,37,b,c
24097,10241,103,38,a,a
24098,10241,103,39,c,b
24099,10241,103,40,e,b

In [16]:
merged_df['option_marked']==merged_df['correct_option']

0        False
1        False
2        False
3        False
4        False
         ...
24095     True
24096    False
24097     True
24098    False
24099    False
Length: 24100, dtype: bool

In [24]:
merged_df.loc[merged_df['option_marked']==merged_df['correct_option'] ,'correct_or_not']  ='correct'

merged_df.loc[merged_df['option_marked']!=merged_df['correct_option'] ,'correct_or_not']  ='incorrect'

merged_df.loc[merged_df['option_marked']=='e' ,'correct_or_not']  ='yet_to_learn'

In [25]:
merged_df

,roll_number,question_paper_code,question_number,option_marked,correct_option,correct_or_not
0,10001,501,1,b,a,incorrect
1,10001,501,2,a,d,incorrect
2,10001,501,3,e,a,yet_to_learn
3,10001,501,4,e,d,yet_to_learn
4,10001,501,5,e,a,yet_to_learn
...,...,...,...,...,...,...
24095,10241,103,36,c,c,correct
24096,10241,103,37,b,c,incorrect
24097,10241,103,38,a,a,correct
24098,10241,103,39,c,b,incorrect
24099,10241,103,40,e,b,yet_to_learn

In [ ]:
# df.loc(condiitom that retuirn boolean series , col_name ]=value assigned

# Jpins the table with subject codes

In [26]:
question_paper_code

   paper_code  class  subject
0         101      6     Math
1         102      7     Math
2         103      8     Math
3         501      6  Science
4         502      7  Science
5         503      8  Science

In [28]:
merged_df=merged_df.merge(question_paper_code,left_on='question_paper_code',right_on='paper_code',how='inner')

In [29]:
merged_df

,roll_number,question_paper_code,question_number,option_marked,correct_option,correct_or_not,paper_code,class,subject
0,10001,501,1,b,a,incorrect,501,6,Science
1,10001,501,2,a,d,incorrect,501,6,Science
2,10001,501,3,e,a,yet_to_learn,501,6,Science
3,10001,501,4,e,d,yet_to_learn,501,6,Science
4,10001,501,5,e,a,yet_to_learn,501,6,Science
...,...,...,...,...,...,...,...,...,...
24095,10241,103,36,c,c,correct,103,8,Math
24096,10241,103,37,b,c,incorrect,103,8,Math
24097,10241,103,38,a,a,correct,103,8,Math
24098,10241,103,39,c,b,incorrect,103,8,Math
24099,10241,103,40,e,b,yet_to_learn,103,8,Math

In [36]:
merged_df[merged_df['roll_number']==10001]['correct_or_not'].value_counts()

correct_or_not
incorrect       64
yet_to_learn    25
correct         11
Name: count, dtype: int64

# Grou[ping the data

In [41]:
temp=merged_df.groupby(['roll_number','subject','correct_or_not'])['paper_code'].count()
temp

roll_number  subject  correct_or_not
10001        Math     correct            5
                      incorrect         27
                      yet_to_learn       8
             Science  correct            6
                      incorrect         37
                                        ..
10241        Math     incorrect         22
                      yet_to_learn       5
             Science  correct           12
                      incorrect         38
                      yet_to_learn      10
Name: paper_code, Length: 1446, dtype: int64

In [42]:
temp.unstack()

correct_or_not       correct  incorrect  yet_to_learn
roll_number subject
10001       Math           5         27             8
            Science        6         37            17
10002       Math          10         25             5
            Science       11         32            17
10003       Math           9         22             9
...                      ...        ...           ...
10239       Science       10         41             9
10240       Math           6         24            10
            Science       11         36            13
10241       Math          13         22             5
            Science       12         38            10

[482 rows x 3 columns]

In [46]:
import warnings
warnings.filterwarnings('ignore')

In [49]:
temp=temp.unstack().unstack()

In [50]:
temp

correct_or_not correct         incorrect         yet_to_learn
subject           Math Science      Math Science         Math Science
roll_number
10001                5       6        27      37            8      17
10002               10      11        25      32            5      17
10003                9      11        22      40            9       9
10004                6      10        23      38           11      12
10005                8       5        25      43            7      12
...                ...     ...       ...     ...          ...     ...
10237                5      15        25      31           10      14
10238                6      14        26      35            8      11
10239                7      10        24      41            9       9
10240                6      11        24      36           10      13
10241               13      12        22      38            5      10

[241 rows x 6 columns]

In [54]:
cols=temp.columns.tolist()

In [55]:
cols

[('correct', 'Math'),
 ('correct', 'Science'),
 ('incorrect', 'Math'),
 ('incorrect', 'Science'),
 ('yet_to_learn', 'Math'),
 ('yet_to_learn', 'Science')]

In [58]:
columns=[f'{item[0]}_{item[1]}' for item in cols]
columns

['correct_Math',
 'correct_Science',
 'incorrect_Math',
 'incorrect_Science',
 'yet_to_learn_Math',
 'yet_to_learn_Science']

In [60]:
temp.columns=columns

In [63]:
temp=temp.reset_index()

In [64]:
temp

,roll_number,correct_Math,correct_Science,incorrect_Math,incorrect_Science,yet_to_learn_Math,yet_to_learn_Science
0,10001,5,6,27,37,8,17
1,10002,10,11,25,32,5,17
2,10003,9,11,22,40,9,9
3,10004,6,10,23,38,11,12
4,10005,8,5,25,43,7,12
...,...,...,...,...,...,...,...
236,10237,5,15,25,31,10,14
237,10238,6,14,26,35,8,11
238,10239,7,10,24,41,9,9
239,10240,6,11,24,36,10,13
240,10241,13,12,22,38,5,10

In [65]:
student_list

     roll_number     student_name  class section           school_name
0          10001          Abhijit      6       A  Google Public School
1          10002            Aghat      6       A  Google Public School
2          10003  Amitava Chandar      6       A  Google Public School
3          10004         Anbarasu      6       A  Google Public School
4          10005       Atralarasu      6       A  Google Public School
..           ...              ...    ...     ...                   ...
236        10237           Oliver      8       C  Google Public School
237        10238            Oscar      8       C  Google Public School
238        10239           Steven      8       C  Google Public School
239        10240           Stuart      8       C  Google Public School
240        10241            Tyler      8       C  Google Public School

[241 rows x 5 columns]

In [67]:
temp=pd.merge(student_list,temp,on='roll_number',how='inner')

In [68]:
temp

,roll_number,student_name,class,section,school_name,correct_Math,correct_Science,incorrect_Math,incorrect_Science,yet_to_learn_Math,yet_to_learn_Science
0,10001,Abhijit,6,A,Google Public School,5,6,27,37,8,17
1,10002,Aghat,6,A,Google Public School,10,11,25,32,5,17
2,10003,Amitava Chandar,6,A,Google Public School,9,11,22,40,9,9
3,10004,Anbarasu,6,A,Google Public School,6,10,23,38,11,12
4,10005,Atralarasu,6,A,Google Public School,8,5,25,43,7,12
...,...,...,...,...,...,...,...,...,...,...,...
236,10237,Oliver,8,C,Google Public School,5,15,25,31,10,14
237,10238,Oscar,8,C,Google Public School,6,14,26,35,8,11
238,10239,Steven,8,C,Google Public School,7,10,24,41,9,9
239,10240,Stuart,8,C,Google Public School,6,11,24,36,10,13
240,10241,Tyler,8,C,Google Public School,13,12,22,38,5,10

In [69]:
temp['correct_Math']

0       5
1      10
2       9
3       6
4       8
       ..
236     5
237     6
238     7
239     6
240    13
Name: correct_Math, Length: 241, dtype: int64

In [74]:
temp['correct_Math']

0       5
1      10
2       9
3       6
4       8
       ..
236     5
237     6
238     7
239     6
240    13
Name: correct_Math, Length: 241, dtype: int64

In [70]:
temp['math_score']=temp['correct_Math']

In [72]:
temp['science_score']=temp['correct_Science']

In [73]:
temp

,roll_number,student_name,class,section,school_name,correct_Math,correct_Science,incorrect_Math,incorrect_Science,yet_to_learn_Math,yet_to_learn_Science,math_score,science_score
0,10001,Abhijit,6,A,Google Public School,5,6,27,37,8,17,5,6
1,10002,Aghat,6,A,Google Public School,10,11,25,32,5,17,10,11
2,10003,Amitava Chandar,6,A,Google Public School,9,11,22,40,9,9,9,11
3,10004,Anbarasu,6,A,Google Public School,6,10,23,38,11,12,6,10
4,10005,Atralarasu,6,A,Google Public School,8,5,25,43,7,12,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,10237,Oliver,8,C,Google Public School,5,15,25,31,10,14,5,15
237,10238,Oscar,8,C,Google Public School,6,14,26,35,8,11,6,14
238,10239,Steven,8,C,Google Public School,7,10,24,41,9,9,7,10
239,10240,Stuart,8,C,Google Public School,6,11,24,36,10,13,6,11
240,10241,Tyler,8,C,Google Public School,13,12,22,38,5,10,13,12

In [79]:
temp['math%']=temp['correct_Math']/(temp['correct_Math']+temp['incorrect_Math']+temp['yet_to_learn_Math'])*100

In [82]:
temp['science%']=temp['correct_Science']/(temp['correct_Science']+temp['incorrect_Science']+temp['yet_to_learn_Science'])*100

In [80]:
temp.columns

Index(['roll_number', 'student_name', 'class', 'section', 'school_name',
       'correct_Math', 'correct_Science', 'incorrect_Math',
       'incorrect_Science', 'yet_to_learn_Math', 'yet_to_learn_Science',
       'math_score', 'science_score', 'math%'],
      dtype='object')

In [86]:
temp['science%']=temp['science%'].apply(lambda x : round(x,2))

In [87]:
temp

,roll_number,student_name,class,section,school_name,correct_Math,correct_Science,incorrect_Math,incorrect_Science,yet_to_learn_Math,yet_to_learn_Science,math_score,science_score,math%,science%
0,10001,Abhijit,6,A,Google Public School,5,6,27,37,8,17,5,6,12.5,10.00
1,10002,Aghat,6,A,Google Public School,10,11,25,32,5,17,10,11,25.0,18.33
2,10003,Amitava Chandar,6,A,Google Public School,9,11,22,40,9,9,9,11,22.5,18.33
3,10004,Anbarasu,6,A,Google Public School,6,10,23,38,11,12,6,10,15.0,16.67
4,10005,Atralarasu,6,A,Google Public School,8,5,25,43,7,12,8,5,20.0,8.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,10237,Oliver,8,C,Google Public School,5,15,25,31,10,14,5,15,12.5,25.00
237,10238,Oscar,8,C,Google Public School,6,14,26,35,8,11,6,14,15.0,23.33
238,10239,Steven,8,C,Google Public School,7,10,24,41,9,9,7,10,17.5,16.67
239,10240,Stuart,8,C,Google Public School,6,11,24,36,10,13,6,11,15.0,18.33
240,10241,Tyler,8,C,Google Public School,13,12,22,38,5,10,13,12,32.5,20.00

In [89]:
roll_no=[10159,10114]

temp[temp['roll_number'].isin(roll_no)]

,roll_number,student_name,class,section,school_name,correct_Math,correct_Science,incorrect_Math,incorrect_Science,yet_to_learn_Math,yet_to_learn_Science,math_score,science_score,math%,science%
113,10114,Dominik,7,B,Google Public School,7,13,24,35,9,12,7,13,17.5,21.67
158,10159,Ada,8,A,Google Public School,4,11,28,38,8,11,4,11,10.0,18.33

In [95]:
list(temp.columns)[::-1]

['science%',
 'math%',
 'science_score',
 'math_score',
 'yet_to_learn_Science',
 'yet_to_learn_Math',
 'incorrect_Science',
 'incorrect_Math',
 'correct_Science',
 'correct_Math',
 'school_name',
 'section',
 'class',
 'student_name',
 'roll_number']

In [97]:
temp[list(temp.columns)[::-1]]

,science%,math%,science_score,math_score,yet_to_learn_Science,yet_to_learn_Math,incorrect_Science,incorrect_Math,correct_Science,correct_Math,school_name,section,class,student_name,roll_number
0,10.00,12.5,6,5,17,8,37,27,6,5,Google Public School,A,6,Abhijit,10001
1,18.33,25.0,11,10,17,5,32,25,11,10,Google Public School,A,6,Aghat,10002
2,18.33,22.5,11,9,9,9,40,22,11,9,Google Public School,A,6,Amitava Chandar,10003
3,16.67,15.0,10,6,12,11,38,23,10,6,Google Public School,A,6,Anbarasu,10004
4,8.33,20.0,5,8,12,7,43,25,5,8,Google Public School,A,6,Atralarasu,10005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,25.00,12.5,15,5,14,10,31,25,15,5,Google Public School,C,8,Oliver,10237
237,23.33,15.0,14,6,11,8,35,26,14,6,Google Public School,C,8,Oscar,10238
238,16.67,17.5,10,7,9,9,41,24,10,7,Google Public School,C,8,Steven,10239
239,18.33,15.0,11,6,13,10,36,24,11,6,Google Public School,C,8,Stuart,10240
240,20.00,32.5,12,13,10,5,38,22,12,13,Google Public School,C,8,Tyler,10241